# Generated by Django 4.2.1 on 2023-05-08 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_message_chat_alter_message_receiver_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Messages',
        ),
    ]
